# Generated by Django 2.1.1 on 2018-10-02 18:24

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nome', models.CharField(help_text='Digite o seu nome', max_length=255, verbose_name='Nome')),
                ('endereco', models.CharField(help_text='Para uma melhor localização no mapa,         preencha sem abreviações.         Ex: Rua taquari,  100', max_length=255, verbose_name='Endereço')),
                ('mensagem', jsonfield.fields.JSONField(blank=True, null=True)),
                ('cidade', models.CharField(blank=True, default='sp', help_text='Para uma melhor localização no mapa,         preencha sem abreviações. Ex: Belo Horizonte', max_length=255, null=True)),
                ('estado', models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, null=True)),
                ('telefone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('rg', models.CharField(max_length=11, verbose_name='RG')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1, verbose_name='Gênero')),
                ('tipo_acesso', models.CharField(choices=[('P', 'Proprietario'), ('E', 'Estudante')], max_length=1, verbose_name='Tipo de acesso')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='imagens/', verbose_name='Fotos')),
                ('data_registro', models.DateField(auto_now_add=True, verbose_name='Registrado em')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Republica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=200, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254)),
                ('endereco', models.CharField(help_text='Para uma melhor localização no mapa,         preencha sem abreviações.         Ex: Rua taquari,  100', max_length=255, verbose_name='Endereço')),
                ('slug', models.SlugField(verbose_name='Atalho')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('A', 'Ambos')], max_length=1, verbose_name='Gênero')),
                ('qtd_vagas', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade de vagas')),
                ('tipo_imovel', models.CharField(max_length=20, verbose_name='tipo de imóvel')),
                ('imagens', models.ImageField(upload_to='imagens/', verbose_name='Fotos')),
                ('data_registro', models.DateField(auto_now_add=True, verbose_name='Registrado em')),
                ('latitude', models.DecimalField(decimal_places=20, default=33, max_digits=30)),
                ('longitude', models.DecimalField(decimal_places=20, default=33, max_digits=30)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('comentarios', models.CharField(blank=True, max_length=1000, null=True)),
                ('mensagem', jsonfield.fields.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'República',
                'verbose_name_plural': 'Repúblicas',
            },
        ),
    ]
