# Generated by Django 2.1.1 on 2018-09-05 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Republica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=200)),
                ('endereco', models.CharField(max_length=200)),
                ('bairro', models.CharField(blank=True, max_length=200)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('A', 'Ambos')], max_length=1)),
                ('qtd_vagas', models.DecimalField(decimal_places=1, max_digits=3)),
                ('tipo_imovel', models.CharField(max_length=20)),
                ('imagens', models.FileField(upload_to='imagens/')),
                ('data_registro', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('endereco', models.CharField(max_length=400)),
                ('telefone', models.CharField(max_length=15)),
                ('rg', models.CharField(max_length=11)),
                ('cpf', models.CharField(max_length=14)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1)),
                ('tipo_acesso', models.CharField(choices=[('P', 'Proprietario'), ('E', 'Estudante')], max_length=1)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
