# Generated by Django 2.1.1 on 2018-10-16 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='republica',
            name='imagens',
            field=models.FileField(upload_to='media/imagens/', verbose_name='Fotos'),
        ),
    ]
