# Generated by Django 2.1.1 on 2018-10-03 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='republica',
            name='rep_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
