# Generated by Django 2.1.1 on 2018-09-25 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='republica',
            name='position',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='position',
        ),
        migrations.AddField(
            model_name='republica',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=-23.55417687, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='republica',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=-46.59599594, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=-23.55167877, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=-46.59762672, max_digits=9),
            preserve_default=False,
        ),
    ]
