# Generated by Django 2.1.1 on 2018-09-25 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20180925_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='republica',
            name='latitude',
            field=models.DecimalField(decimal_places=28, max_digits=30),
        ),
        migrations.AlterField(
            model_name='republica',
            name='longitude',
            field=models.DecimalField(decimal_places=28, max_digits=30),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='latitude',
            field=models.DecimalField(decimal_places=28, max_digits=30),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='longitude',
            field=models.DecimalField(decimal_places=28, max_digits=30),
        ),
    ]
