# Generated by Django 2.1.1 on 2018-09-06 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20180906_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='republica',
            name='imagens',
            field=models.ImageField(upload_to='imagens/'),
        ),
    ]
