# Generated by Django 2.1.1 on 2018-09-27 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20180927_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='republica',
            name='email',
            field=models.EmailField(default='guiilherme.t36@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
