# Generated by Django 2.1.1 on 2018-09-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_republica_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='mensagem',
            field=models.CharField(blank=True, help_text='Digite uma mensagem', max_length=10000, null=True, verbose_name='Mensagem'),
        ),
    ]
