# Generated by Django 2.1.1 on 2018-11-19 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20181017_1953'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.TextField(verbose_name='Description')),
                ('pergunta_datetime', models.DateTimeField(verbose_name='Quando foi realizada a Pergunta')),
                ('resposta', models.TextField(blank=True, null=True, verbose_name='Quando foi Respondido')),
                ('resposta_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Created At')),
                ('republica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagem_republica', to='mysite.Republica')),
                ('usuario_pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagem_usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mensagem',
                'verbose_name_plural': 'Mensagens',
            },
        ),
    ]
