# Generated by Django 2.1.1 on 2018-09-27 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_auto_20180927_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nome',
            field=models.CharField(default='luis', help_text='Digite o seu nome', max_length=255, verbose_name='Nome'),
            preserve_default=False,
        ),
    ]
