# Generated by Django 2.1.1 on 2018-11-20 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_mensagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagem',
            name='pergunta_datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Quando foi realizada a Pergunta'),
        ),
    ]
