# Generated by Django 2.1.1 on 2018-09-06 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_usuario_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='republica',
            name='qtd_vagas',
            field=models.IntegerField(),
        ),
    ]
