# Generated by Django 2.1.1 on 2018-09-06 16:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_auto_20180906_0044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='republica',
            options={'verbose_name': 'República', 'verbose_name_plural': 'Repúblicas'},
        ),
        migrations.AddField(
            model_name='republica',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, verbose_name='Atalho'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='data_registro',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Registrado em'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='republica',
            name='bairro',
            field=models.CharField(blank=True, max_length=200, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='republica',
            name='data_registro',
            field=models.DateField(auto_now_add=True, verbose_name='Registrado em'),
        ),
        migrations.AlterField(
            model_name='republica',
            name='endereco',
            field=models.CharField(max_length=200, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='republica',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('A', 'Ambos')], max_length=1, verbose_name='Gênero'),
        ),
        migrations.AlterField(
            model_name='republica',
            name='imagens',
            field=models.ImageField(upload_to='imagens/', verbose_name='Fotos'),
        ),
        migrations.AlterField(
            model_name='republica',
            name='nome',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='republica',
            name='tipo_imovel',
            field=models.CharField(max_length=20, verbose_name='tipo de imóvel'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(max_length=14, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='endereco',
            field=models.CharField(max_length=400, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1, verbose_name='Gênero'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='imagens/', verbose_name='Fotos'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nome',
            field=models.CharField(max_length=200, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rg',
            field=models.CharField(max_length=11, verbose_name='RG'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(max_length=15, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_acesso',
            field=models.CharField(choices=[('P', 'Proprietario'), ('E', 'Estudante')], max_length=1, verbose_name='Tipo de acesso'),
        ),
    ]
