# Generated by Django 2.1.1 on 2018-11-27 13:31

from django.db import migrations, models
import django.db.models.deletion
import mysite.models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_auto_20181120_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagensRepublica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=mysite.models.get_image_filename, verbose_name='Image')),
                ('republica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagem_republica', to='mysite.Republica')),
            ],
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='pergunta',
            field=models.TextField(verbose_name='Pergunta'),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='resposta',
            field=models.TextField(blank=True, null=True, verbose_name='Resposta Proprietario'),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='resposta_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Quando foi Respondido'),
        ),
    ]
