# Generated by Django 2.1.1 on 2018-09-06 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_auto_20180906_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='republica',
            name='qtd_vagas',
            field=models.IntegerField(verbose_name='Quantidade de vagas'),
        ),
    ]
