# Generated by Django 2.1.1 on 2018-12-11 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_auto_20181127_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagensrepublica',
            name='image',
            field=models.ImageField(upload_to='media/imagens/', verbose_name='Fotos'),
        ),
    ]
